title: Mohamed's Blog
author: Mohamed-Magdey
email: ragabmohame6@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  demo blog.

# social links
github_username:  Mohamed-Magdey # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
